### ISSUE TITLE
Unprocessable Entity when updating Github

### ISSUE THREAD

**Issue by qnm** [gimenete/rubocop-action#2]
When running this check, I'm hitting the following error:

```
/action/lib/index.rb:63:in `update_check': Unprocessable Entity (RuntimeError)
	from /action/lib/index.rb:125:in `run'
	from /action/lib/index.rb:134:in `<main>'
```

Any ideas? Nothing prior to indicate any specific failures in Rubocop.

**Comment by dnorth98** [comment]
Exactly the same problem here.  I actually created an issue on the fork of this repo

https://github.com/andrewmcodes/rubocop-linter-action/issues/16

with the same problem.  @qnm are you using a private repo by any chance?  I theorized that is maybe the problem.

Rubocop runs just fine but it's when it's posting back to Github that it gets the error.

**Comment by dnorth98** [comment]
I think I see the problem.  I posted this on andrew's repo but I'll post the same here as I think it's the same problem:

So in the docs for updating a check:

https://developer.github.com/v3/checks/runs/

it says that:

> Warning: The API may change without advance notice during the preview period. Preview features are not supported for production use. If you experience any issues, contact

 I think the API has changed :) . Looking in the code when the check is updated, it's passing:

```
 body = {
    "name" => @check_name,
    "head_sha" => @GITHUB_SHA,
    "status" => 'completed',
    "completed_at" => Time.now.iso8601,
    "conclusion" => conclusion,
    "output" => output
```

yet `head_sha` isn't a valid field in the github docs.  I wonder if it used to be and now it's not?  It IS valid on a create of a check but not on an update.  The docs do say:

> Sending invalid fields will result in a 422 Unprocessable Entity response.

Thinking that may be it!
